[icedos.applications]
extraPackages = ["anydesk", "beekeeper-studio", "brave", "ddev", "epiphany"]
aagl = false
android-tools = false
celluloid = true
clamav = false
defaultBrowser = "zen" # Options: 'librewolf', 'zen'
defaultEditor = "zed" # Options: 'codium', 'zed'
input-remapper = true
librewolf = false
nautilus = true
php = true
rust = false
solaar = true
ssh = true
sunshine = false

[icedos.applications.codium]
enable = true
zoomLevel = 0

[icedos.applications.kitty]
enable = true
hideDecorations = false # Hide top bar

[icedos.applications.mangohud]
enable = false

[icedos.applications.network-manager]
enable = true
applet = true

[icedos.applications.obs-studio]
enable = true
virtualCamera = false

[icedos.applications.signal]
enable = false

[icedos.applications.steam]
enable = false

[icedos.applications.steam.session]
enable = false

[icedos.applications.steam.session.autoStart]
enable = false

[icedos.applications.tailscale]
enable = false

[icedos.applications.valent]
enable = false

[icedos.applications.zed]
enable = true
ollamaSupport = false
vim = true

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # Options: 'system', 'dark', 'light'

[icedos.applications.zen-browser]
enable = true
privacy = true

[[icedos.applications.zen-browser.profiles]]
default = true
exec = "default"
pwa = false

[[icedos.applications.zen-browser.profiles]]
default = false
exec = "dtek"
pwa = false

[[icedos.applications.zen-browser.profiles]]
default = false
exec = "zen-social"
pwa = true
icon = "zen"
name = "Zen Social"

sites = [
  "https://mail.proton.me",
  "https://develop.element.io",
  "https://discord.com/app",
  "https://dtekteam.slack.com/",
  "https://teams.live.com/v2/",
]

[icedos.bootloader]
animation = true # Hides console and displays a loading interface based on OEM on boot

[icedos.bootloader.grub]
enable = false
device = "/dev/sda"

[icedos.bootloader.systemd-boot]
enable = true
mountPoint = "/boot"

[icedos.desktop]
accentColor = "7E57C2" # With gnome enabled this is getting overriden by gnome's selected accent color hex code

[icedos.desktop.autologin]
enable = true
user = "dtek"

[icedos.desktop.gdm]
enable = true
autoSuspend = true

[icedos.desktop.gnome]
enable = false

[icedos.desktop.hyprland]
enable = true
followMouse = 1 # Options: https://wiki.hyprland.org/Configuring/Variables/#follow-mouse-cursor
hyprspace = false

startupScript = """
run zen
run zen-social
nautilus -w &
nautilus -w &
run steam
run flare
run zeditor
kitty --class task-managers btop &
kitty --class terminals tmux new -s terminals \\; split-window -v \\; select-pane -U \\; split-window -h \\; select-pane -D &
"""

windowRules = [
  "workspace 1 silent, class:^(zen)$",
  "workspace 2 silent, class:^(dev.zed.Zed)$",
  "workspace 11 silent, class:^(de.schmidhuberj.Flare|zen-social)$",
  "workspace 12 silent, class:^(org\\.gnome\\.Nautilus)$",
  "workspace 13 silent, class:^(task-managers)$",
  "workspace 14 silent, class:^(terminals)$",
]

[icedos.desktop.hyprland.cs2fix]
enable = false

[icedos.desktop.hyprland.hyproled]
enable = false

[icedos.desktop.hyprland.lock]
secondsToLowerBrightness = 60
cpuUsageThreshold = 60 # CPU usage to inhibit lock in percentage
diskUsageThreshold = 10 # Disk usage to inhibit lock in MB/s
networkUsageThreshold = 1_000_000 # Network usage to inhibit lock in bytes/s

[icedos.hardware]
bluetooth = true

[[icedos.hardware.mounts]]
path = "/"
device = "/dev/disk/by-uuid/07ced491-ddcf-4733-b780-02d3e7b931f9"
fsType = "btrfs"
flags = ["compress=zstd", "nofail", "x-gvfs-show"]

[icedos.hardware.cpus]
intel = false

[icedos.hardware.cpus.amd]
enable = true
zenpower = false # Report watt usage for apps e.g. mangohud

[icedos.hardware.cpus.amd.undervolt]
enable = false

[icedos.hardware.devices]
laptop = false
steamdeck = false

[icedos.hardware.drivers]
rtl8821ce = false # Use the unofficial RTL8821CE driver

[icedos.hardware.devices.server]
enable = false

[icedos.hardware.gpus.amd]
enable = true
rocm = false

[icedos.hardware.gpus.nvidia]
enable = false

[[icedos.hardware.monitors]]
name = "HDMI-A-1"
disable = false
resolution = "1920x1080"
refreshRate = 60
position = "0x0"
scaling = 1
rotation = 0
tenBit = false

[[icedos.hardware.monitors]]
name = "DP-3"
disable = false
resolution = "1920x1080"
refreshRate = 60
position = "-1920x0"
scaling = 1
rotation = 0
tenBit = false

[icedos.hardware.networking]
hostname = "desktop-dtek"
hosts = "192.168.2.99 git.dtek.gr"
ipv6 = false
vpnExcludeIp = "192.168.1.200"

[icedos.hardware.networking.wg-quick]
enable = false

[icedos.system]
channels = [] # https://github.com/NixOS/nixpkgs/branches/active
forceFirstBuild = false
home = "/home"
kernel = "cachyos" # Options: 'cachyos', 'cachyos-server', 'latest', 'lts', 'valve', 'zen'
swappiness = 1
version = "23.05" # Do not change without checking the docs (config.system.stateVersion)

[icedos.system.generations]
bootEntries = 10

[icedos.system.generations.garbageCollect]
automatic = true
days = 0 # Number of days before a generation can be deleted
generations = 10 # Number of generations that will always be kept
interval = "Mon *-*-* 00:00:00" # Format(https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html)

[icedos.system.users.dtek]
description = "dtek"
type = "main" # Options: 'main', 'work', 'server'

[icedos.system.users.dtek.applications.codium]
autoSave = "off" # Options: 'off', 'afterDelay', 'onFocusChange', 'onWindowChange'
formatOnSave = false
formatOnPaste = false

[icedos.system.users.dtek.applications.git]
username = "IceDBorn"
email = "git.outsider841@simplelogin.fr"

[icedos.system.users.dtek.desktop.idle.lock]
enable = true
seconds = 180

[icedos.system.users.dtek.desktop.idle.disableMonitors]
enable = true
seconds = 900

[icedos.system.users.dtek.desktop.idle.suspend]
enable = true
seconds = 1800

[icedos.system.virtualisation]
virtManager = false
waydroid = false

[icedos.system.virtualisation.containerManager]
enable = true
usePodman = false
requireSudoForDocker = false # CAUTION: Disabling this gives every user root priviledges!
