[icedos.applications]
extraPackages = []
insecurePackages = []
aagl = false
android-tools = false
celluloid = false
clamav = false
defaultBrowser = "zen" # Options: 'librewolf', 'zen'
defaultEditor = "zed" # Options: 'codium', 'zed'
input-remapper = false
librewolf = false
nautilus = false
php = false
rust = false
solaar = false
ssh = true
sunshine = false

[icedos.applications.codium]
enable = false

[icedos.applications.kitty]
enable = false

[icedos.applications.mangohud]
enable = false

[icedos.applications.network-manager]
enable = false

[icedos.applications.obs-studio]
enable = false

[icedos.applications.signal]
enable = false

[icedos.applications.steam]
enable = false

[icedos.applications.steam.session]
enable = false

[icedos.applications.tailscale]
enable = false

[icedos.applications.valent]
enable = false

[icedos.applications.zed]
enable = false
ollamaSupport = false
vim = true

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # Options: 'system', 'dark', 'light'

[icedos.applications.zen-browser]
enable = false
privacy = true

[icedos.bootloader]
animation = true # Hides console and displays a loading interface based on OEM on boot

[icedos.bootloader.grub]
enable = false
device = "/dev/sda"

[icedos.bootloader.systemd-boot]
enable = true
mountPoint = "/boot"

[icedos.desktop]
accentColor = "7E57C2" # With gnome enabled this is getting overriden by gnome's selected accent color hex code

[icedos.desktop.autologin]
enable = false
user = "server"

[icedos.desktop.gdm]
enable = false

[icedos.desktop.gnome]
enable = false

[icedos.desktop.hyprland]
enable = false

[icedos.hardware]
bluetooth = false
monitors = []

[[icedos.hardware.mounts]]
path = "/"
device = "/dev/disk/by-uuid/f62cb4c9-af51-41a6-9a5f-2500ec2bf048"
fsType = "btrfs"
flags = ["compress=zstd", "nofail", "x-gvfs-show"]

[icedos.hardware.cpus]
intel = true

[icedos.hardware.cpus.amd]
enable = false

[icedos.hardware.devices]
laptop = false
server = true
steamdeck = false

[icedos.hardware.drivers]
rtl8821ce = false # Use the unofficial RTL8821CE driver

[icedos.hardware.gpus.amd]
enable = false

[icedos.hardware.gpus.nvidia]
enable = false

[icedos.hardware.networking]
hostname = "server"
hosts = ""
ipv6 = false
vpnExcludeIp = "192.168.1.240"

[icedos.hardware.networking.wg-quick]
enable = true
interfaces = ["protonvpn"]

[icedos.system]
channels = [] # https://github.com/NixOS/nixpkgs/branches/active
forceFirstBuild = false
home = "/home"
kernel = "cachyos-server" # Options: 'cachyos', 'cachyos-server', 'latest', 'lts', 'valve', 'zen'
swappiness = 1
version = "23.05" # Do not change without checking the docs (config.system.stateVersion)

[icedos.system.generations]
bootEntries = 10

[icedos.system.generations.garbageCollect]
automatic = true
days = 0 # Number of days before a generation can be deleted
generations = 10 # Number of generations that will always be kept
interval = "Mon *-*-* 00:00:00" # Format(https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html)

[icedos.system.users.server]
description = "server"
type = "server" # Options: 'main', 'work', 'server'

[icedos.system.users.server.applications.git]
username = "IceDBorn"
email = "git.outsider841@simplelogin.fr"

[icedos.system.virtualisation]
virtManager = false
waydroid = false

[icedos.system.virtualisation.containerManager]
enable = true
usePodman = false
requireSudoForDocker = true # CAUTION: Disabling this gives every user root priviledges!
