{
  inputs = {
    # Package repositories
    chaotic.url = "github:chaotic-cx/nyx/nyxpkgs-unstable";

    nixpkgs.follows = "chaotic/nixpkgs";

    # Modules
    home-manager = {
      url = "github:nix-community/home-manager";

      follows = "chaotic/home-manager";

    };

    nerivations = {
      url = "github:icedborn/nerivations";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    steam-session.follows = "chaotic/jovian";

    # Apps

    zen-browser = {
      url = "github:0xc000022070/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

  };

  outputs =
    {
      home-manager,
      nerivations,
      nixpkgs,
      self,

      chaotic,

      steam-session,
      zen-browser,
      ...
    }@inputs:
    {
      nixosConfigurations."deck" = nixpkgs.lib.nixosSystem rec {
        system = "x86_64-linux";

        specialArgs = {
          inherit inputs;
        };

        modules = [
          # Read configuration location
          (
            { lib, ... }:
            let
              inherit (lib) mkOption types;
            in
            {
              options.icedos.configurationLocation = mkOption {
                type = types.str;
                default = "/home/deck/.code/icedos";
              };
            }
          )

          # Symlink configuration state on "/run/current-system/source"
          {
            # Source: https://github.com/NixOS/nixpkgs/blob/5e4fbfb6b3de1aa2872b76d49fafc942626e2add/nixos/modules/system/activation/top-level.nix#L191
            system.extraSystemBuilderCmds = "ln -s ${self} $out/source";
          }

          # Internal modules
          (
            { lib, ... }:
            let
              inherit (lib) filterAttrs;

              getModules =
                path:
                map (dir: "/${path}/${dir}") (
                  let
                    inherit (lib) attrNames;
                  in
                  attrNames (
                    filterAttrs (n: v: v == "directory" && !(n == "desktop" && path == ./system)) (
                      builtins.readDir path
                    )
                  )
                );
            in
            {
              imports =
                [
                  ./hardware
                  ./internals.nix
                  ./options.nix
                ]
                ++ getModules (./system)
                ++ getModules (./hardware);

              config.system.stateVersion = "23.05";
            }
          )

          # External modules
          chaotic.nixosModules.default
          ./hardware/graphics/modules/mesa

          home-manager.nixosModules.home-manager
          nerivations.nixosModules.default

          ./system/desktop

          # Is First Build
          { icedos.internals.isFirstBuild = false; }

          steam-session.nixosModules.default
          ./system/desktop/steam-session

          ./system/desktop/gnome

          ./system/applications/modules/zen-browser

          (
            # Do not modify this file!  It was generated by ‘nixos-generate-config’
            # and may be overwritten by future invocations.  Please make changes
            # to /etc/nixos/configuration.nix instead.
            {
              config,
              lib,
              pkgs,
              modulesPath,
              ...
            }:

            {
              imports = [
                (modulesPath + "/installer/scan/not-detected.nix")
              ];

              boot.initrd.availableKernelModules = [
                "nvme"
                "xhci_pci"
                "usbhid"
                "sdhci_pci"
              ];
              boot.initrd.kernelModules = [ "dm-snapshot" ];
              boot.kernelModules = [ "kvm-amd" ];
              boot.extraModulePackages = [ ];

              fileSystems."/" = {
                device = "/dev/disk/by-uuid/b9f8f130-fa10-4eba-a75c-e35b97a67b7d";
                fsType = "btrfs";
                options = [ "subvol=@root" ];
              };

              fileSystems."/home" = {
                device = "/dev/disk/by-uuid/b9f8f130-fa10-4eba-a75c-e35b97a67b7d";
                fsType = "btrfs";
                options = [ "subvol=@home" ];
              };

              fileSystems."/boot" = {
                device = "/dev/disk/by-uuid/C97E-DF49";
                fsType = "vfat";
              };

              fileSystems."/var/lib/lxd/shmounts" = {
                device = "tmpfs";
                fsType = "tmpfs";
              };

              fileSystems."/var/lib/lxd/devlxd" = {
                device = "tmpfs";
                fsType = "tmpfs";
              };

              swapDevices = [ ];

              # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
              # (the default) this is the recommended approach. When using systemd-networkd it's
              # still possible to use this option, but it's recommended to use it in conjunction
              # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
              networking.useDHCP = lib.mkDefault true;
              # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
              # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
              # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

              nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
              hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            }
          )

          (
            { ... }:
            {
              boot.initrd = {
                luks.devices.os = {
                  device = "/dev/disk/by-uuid/9ad27aa5-dc73-4c24-ad1c-54f7306f133c";
                  allowDiscards = true;
                  preLVM = true;
                };
              };

              swapDevices = [ { device = "/dev/disk/by-uuid/606d06b9-532e-42fc-b9ef-43a45c3512b6"; } ];
            }
          )

        ];
      };
    };
}
