# Generated by ./update.sh - do not update manually!
# Last updated: 2023-05-26
{
  compatList = {
    rev = "b035ce2506f7475db97c061c7cdfa40985283a80";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1446";
    hash = "sha256:041kzrjkf58mkk8c38zziivfz40wjn78xgi59k79f4gl99zjgawg";
  };

  ea = {
    version = "3614";
    distHash = "sha256:06r8l1d2hg1gaz50aqqv3pfi5ik8x2rpn8dbqaa64gmkbhmh6rpp";
    fullHash = "sha256:11h7g0fq1x04q5gga404l9dp5rc86zxjcf7qhgps4ml6kp7gvbym";
  };
}
