# Generated by ./update.sh - do not update manually!
# Last updated: 2023-05-28
{
  compatList = {
    rev = "8392f031d530b567245bef3f04618f9f08f3892d";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1448";
    hash = "sha256:0r1ykc764qsimryil4inw4j5x1f4rq9jc9288z4kyw4pl800g48n";
  };

  ea = {
    version = "3618";
    distHash = "sha256:0q81y231nv4wmdlr3s3j41wk6xp9j89rlxq84n5v4j297qy4kpad";
    fullHash = "sha256:1xdrkw7qrra88750mmqcbn1sxzvmz3nrn28n76zfszf9661154cx";
  };
}
