# Generated by ./update.sh - do not update manually!
# Last updated: 2023-05-27
{
  compatList = {
    rev = "ca6f890cc2be81eac00853bab32cbb3999f54d55";
    hash = "sha256:1hdsza3wf9a0yvj6h55gsl7xqvhafvbz1i8paz9kg7l49b0gnlh1";
  };

  mainline = {
    version = "1447";
    hash = "sha256:041kzrjkf58mkk8c38zziivfz40wjn78xgi59k79f4gl99zjgawg";
  };

  ea = {
    version = "3617";
    distHash = "sha256:0s4vph87n3ydkq2snlydg6nrjd9jmxxzky095apfydb6zvcjjyfh";
    fullHash = "sha256:02gag1wqhffllx2vgq7akjim9b1n6g7pjmij11rm4w790hr3rw3h";
  };
}
